/*
 *
 * Collection constants
 *
 */


export const COLLECTION_ARTICLE_START = `COLLECTION_ARTICLE_START`;
export const COLLECTION_ARTICLE_SUCCESS = `COLLECTION_ARTICLE_SUCCESS`;
export const COLLECTION_ARTICLE_ERROR = `COLLECTION_ARTICLE_ERROR`;

export const COLLECTION_VIDEO_START = `COLLECTION_VIDEO_START`;
export const COLLECTION_VIDEO_SUCCESS = `COLLECTION_VIDEO_SUCCESS`;
export const COLLECTION_VIDEO_ERROR = `COLLECTION_VIDEO_ERROR`;